### ISSUE TITLE
Webページの概観について

### ISSUE THREAD

**Issue by m-star18** [Gin-mmsm/image-calculator#11]
見た目はとりあえず置いといての仮の案なのですがどうでしょうか

![12671587410702](https://user-images.githubusercontent.com/52071380/93014405-d0f41c00-f5eb-11ea-9260-63b2c6f24049.jpg)

**Comment by Gin-mmsm** [comment]
遷移後もまた画像選べるってことかな？
戻るボタンの方が実装楽そうかなと思ったんだけどどうだろう...？

**Comment by m-star18** [comment]
そんな感じです！
戻るボタンも考えたのですが使いやすそうな方を選びました〜

**Comment by Gin-mmsm** [comment]
なるほど！そこも考えての案なら大丈夫と思う！

**Comment by m-star18** [comment]
ありがとうございます！
