### ISSUE TITLE
提案

### ISSUE THREAD

**Issue by Gin-mmsm** [Gin-mmsm/image-calculator#16]
engでもjpnでも(おそらく)同じ結果になることがわかったので(自分が間違えてるかもですが...)、+, -, ×に絞って、oやO(オー)を0(ゼロ)にしたり、xやX(エックス)を×(かけ)に読み換えることでまあまあ良い精度で実現できると思ったんですが、どうでしょうか...？

**Comment by Gin-mmsm** [comment]
あ、jpnよりengの方が良さそう...
÷を抜いたのは、これがうまく認識されなそう(サンプル数1だけど)だからです

**Comment by m-star18** [comment]
> engでもjpnでも(おそらく)同じ結果になることがわかったので(自分が間違えてるかもですが...)、+, -, ×に絞って、oやO(オー)を0(ゼロ)にしたり、xやX(エックス)を×(かけ)に読み換えることでまあまあ良い精度で実現できると思ったんですが、どうでしょうか...？

良いと思います！➗はどうしましょうね、、、

**Comment by Gin-mmsm** [comment]
んー...後回しにしてしまうのも手かな...

**Comment by m-star18** [comment]
後からでも機能は追加できそうなのでそれでもいいと思います！
Webの方も水曜日頃に一気に完成させる予定なので大丈夫だと思います

**Comment by atsuki0727** [comment]
https://github.com/tesseract-ocr/tessdata_fast/issues/4

数式用のequ.traineddataはなくなってしまった（泣）らしいのでそれがよさそうですね

**Comment by m-star18** [comment]
提案
calculator.pyが長くなってきたのでテスト部分をtest.pyに移行しませんか

**Comment by Gin-mmsm** [comment]
確かに... @atsuki0727 がリアクションしてくれてるみたいだし、お願いしてもいいかな？
