### ISSUE TITLE
もしできたら実装したいこと

### ISSUE THREAD

**Issue by Gin-mmsm** [Gin-mmsm/image-calculator#28]
- thresholdの値を変える
- 読み取った結果の画像(赤ワクで囲んだやつ)の表示
- 文字のキーボード上での打ち直し

**Comment by m-star18** [comment]
thresholdはどのような役割を持っていますか
文字のキーボード上での打ち直し機能は実装大丈夫そうです

**Comment by Gin-mmsm** [comment]
- threshold は二値化するときの閾値で(コンピュータ上で書いた白黒だとあんま結果変わらなそうだけど)その値より明るいのを白(255)、暗いのを黒(0)ってやっちゃう値です！これで結果変わることもよくあるので...
- それできたら利便性上がりそうだからやって欲しいかも！

**Comment by Gin-mmsm** [comment]
赤ワクの表示もちょっと自分で考えてみます！(わかんなかったらきく！笑)

**Comment by m-star18** [comment]
なるほど！よろしくお願いします
