### ISSUE TITLE
staticってどこ？

### ISSUE THREAD

**Issue by Gin-mmsm** [Gin-mmsm/image-calculator#36]
static_folder って 'static/' でいいよね？
で、ここは自分の知識不足のせいなんだけど、css は読めるようになるんだけど、img のパスがうまく通らなくなってしまう...

**Comment by Gin-mmsm** [comment]
もしかして、staticにないと読めない仕様...？

**Comment by m-star18** [comment]
assetsフォルダにアップロードされた写真を保存する様にしてたのでわざと変更してました。
staticにするなら__init__.pyのstatic_folderはいじらなくて大丈夫です🙇‍♂️
