### ISSUE TITLE
ファイルを選択せずに計算したとき

### ISSUE THREAD

**Issue by Gin-mmsm** [Gin-mmsm/image-calculator#38]
なんかバグる...？(もしかして自分のpushミスのあたりでなんかやらかしたかな...

**Comment by m-star18** [comment]
なんて表示されますか、、？
想定ではNotFoundError的なのが出てくれると思います

**Comment by Gin-mmsm** [comment]
FileNotFoundError!!が表示されるのもみたことあるんだけど、今はwerkzeug.exceptions.BadRequestKeyError になっちゃう...

**Comment by Gin-mmsm** [comment]
upLoadFile ないのにfileを読み込もうとしてるのかな...？

**Comment by m-star18** [comment]
特におかしいところは無さそうなので困りました

**Comment by Gin-mmsm** [comment]
idを設定しちゃったのがバグってたみたい

**Comment by m-star18** [comment]
なるほど、助かりました🙌
