### ISSUE TITLE
レビューについて

### ISSUE THREAD

**Issue by m-star18** [Gin-mmsm/image-calculator#4]
やる事毎にissueを用意する(タスク)
↓
基本の担当はあるが余裕があればお互いのissueも取り組む(やる時はコメントを残しておくと上手くいきそうです)
↓
作業用ブランチを作る
feature/タスク名　など
↓
完成したらプルリクエストを出す
↓
誰か1人にレビューしてもらう
↓
良ければdevlopブランチにマージする

最後に完成したらmasterブランチへ！
の開発の流れでどうでしょうか。

現在他の人はプルリクエストを送ったりissueを用意する事は出来ますが、レビューやマージは出来ないので設定を変更出来そうならお願いしたいです。

レビューなど参考リンクです。
https://docs.github.com/ja/github/collaborating-with-issues-and-pull-requests/reviewing-proposed-changes-in-a-pull-request

**Comment by m-star18** [comment]
developブランチは削除されました
ありがとうございます！
もしバグが出たりして困ったら
fix/タスク名でブランチを切ってプルリクエストを送るようにするのはどうでしょうか

**Comment by Gin-mmsm** [comment]
あ、mdの変更pushし忘れてたからdevelopにまたpushしてしまった...笑
deployが正常にできてからそうしてく感じでいいかな？

**Comment by m-star18** [comment]
大丈夫だと思います🙆‍♂️
