### ISSUE TITLE
ファイルが混合している

### ISSUE THREAD

**Issue by m-star18** [Gin-mmsm/image-calculator#8]
ファイル名を変更するときにsrcファイルとmainファイルで混ざってしまいました。
今から直します！

**Comment by m-star18** [comment]
- [x] main/calculatorをsrc/calculatorに変更
- [x] mainフォルダの削除 --- 困ってます

**Comment by Gin-mmsm** [comment]
今どんな状況なんだろ...？

**Comment by m-star18** [comment]
developブランチを見るとわかるのですがさっきのプルリクエストで変更したmain->srcへの変更が一部うまくいかずに混ざってる感じです。
remote上のdirectoryは消せないのでとりあえず思いついたのは全て一度消す方法ですが、あまり良く無いですね。。

https://qiita.com/expajp/items/fe50fb57ccc7e43d6291

**Comment by Gin-mmsm** [comment]
今mainにあるやつを全部srcにしたかったけど、それができてなかったってことか...

**Comment by m-star18** [comment]
一度calculator.pyを消すと上手くいきそうなのでやってみます！

**Comment by Gin-mmsm** [comment]
ちゃんと消えてるね

**Comment by m-star18** [comment]
良かったです！
ありがとうございました
